### ISSUE TITLE
AP50% and Times

### ISSUE THREAD

**Issue by rouge012** [YuHengsss/YOLOV#49]
Hi! which file did you calculate the AP and Times? I want to reproduce them and calculate other metrics.

Thanks a lot!

**Comment by YuHengsss** [comment]
hello，for AP50 calculation, you could obtain the result following the process of "Reproduce our results on VID" in the readme file.  
For time measurement, please refer to https://github.com/YuHengsss/YOLOV/blob/47237acf12ddd6a6173a079b789a0cb38ffb0da7/tools/vid_demo.py#L138 . It's worth to mention that this time varies from different CPU because of the post-processing procedure and "TopK" sorting.

**Comment by Hikaylee** [comment]
> hello，for AP50 calculation, you could obtain the result following the process of "Reproduce our results on VID" in the readme file. For time measurement, please refer to
> 
> https://github.com/YuHengsss/YOLOV/blob/47237acf12ddd6a6173a079b789a0cb38ffb0da7/tools/yolov_demo_online.py#L141
> 
> It's worth to mention that this time varies from different CPU because of the post-processing procedure and "TopK" sorting.


您好，我想请问一下为什么用vid_eval和REPPM两种评估的精度差别这么大呢？

**Comment by YuHengsss** [comment]
> > hello，for AP50 calculation, you could obtain the result following the process of "Reproduce our results on VID" in the readme file. For time measurement, please refer to
> > https://github.com/YuHengsss/YOLOV/blob/47237acf12ddd6a6173a079b789a0cb38ffb0da7/tools/yolov_demo_online.py#L141
> > 
> > It's worth to mention that this time varies from different CPU because of the post-processing procedure and "TopK" sorting.
> 
> 您好，我想请问一下为什么用vid_eval和REPPM两种评估的精度差别这么大呢？

应该是 VID AP@50 与 COCO API 不太一样造成的，在我们的测试中，会差大约0.5～0.7个点
